### ISSUE TITLE
Removed check if value has changed before updating devices

### ISSUE THREAD

**Issue by michass** [mvzut/maxcube-Domoticz-plugin#1]
Hi, why did you remove this condition check?

**Comment by mvzut** [comment]
Hi, on my own setup, I found that the day graphs were empty for e.g. the valve positions. Because they had been at 0% for the past few days, they didn't need an update according to my code. However, Domoticz doesn't plot a nice line at zero if it hasn't been updated for a few days. Since I removed this check, my graphs look normal again.
Building in checks like these was basically an old habit that I inherited from when I was writing Lua or shell scripts, where I tried to minimize the amount of communication with Domoticz. However, in a Python plugin, this is not really necessary, it doesn't form a real load for the system.
Would you rather have the check back in? I could even make it into a configurable parameter.

**Comment by michass** [comment]
Hi, thanks for your answear,
configurable check if will should be good idea.

**Comment by michass** [comment]
I have a question:
You Remove condition, and domoticz devices are updated for for example 5min, but you don't send update to cube, or do you?

**Comment by mvzut** [comment]
Hi,

The update of the Domoticz devices is based on info FROM the Cube, e.g. valve positions, temperatures, etc. So this doesn't need updates on the Cube. When the user changes the value of a mode or setpoint, this is captured by another part of the plugin, which acts independent of the polling time, and sends the update to the Cube immediately.

I hope this makes it more clear?

By the way, I am considering to put the check back in again, since now you cannot see from the last update time when a device really changed its value for the last time. I later realized that this is something people might use the "last update" timestamp for. 

Martijn

**Comment by mvzut** [comment]
I have put the check back in in the last version!

**Comment by michass** [comment]
But i see, that I have in some rooms, that i don't use often same temp on Comfort and Eco program(17C).
If i need to use room, then I need to set temperature manually, and when comfort or eco switch, then go back to 17C. Can you add condition, when actual temp = new setpoint, then do nothing?
When i try to set all radiators at one time, then I have:
`EQ-3 hardware (11) thread seems to have ended unexpectedly`

Maybe if the pulgin will skip devices, with no changes, could improve.

**Comment by mvzut** [comment]
Do you mean that I should build in a check which does NOT change the setpoint if the actual room temperature is already equal or higher then the setpoint? That would be a bad idea I believe.

What I could do, is make sure that “new" setpoints which are not different from the previous one are not written to the Cube again. If you use a script to set a lot of setpoints at the same time, and many have not really changed, this will indeed save some time.

I have just uploaded a new version to Github which has this check implemented.

**Comment by michass** [comment]
Not check, than eqal or higher, but new setpoint is the same as actual setpoint. Every 5 minutes your script check, values of setpoints for all units. Even, when i change setpoint manually on radiator, then script should know that. If 5 minutes is to much time, we can change for 1 min.

**Comment by mvzut** [comment]
I’m sorry, but I am not sure what you mean.

Anyway, I think the new version should already be an improvement: it only communicates with the Cube when the new setpoint is actually NEW, i.e. when it is not the same as it already was. This will help reduce communication with the Cube, especially if the setpoint for some thermostats does not change with your script.

Now that I read your mail again, maybe you mean that I should only send new values every 5 minutes? This is not how the Python plugin framework works unfortunately, when a setpoint is changed, this is handled immediately. I could in theory collect all changes for 5 minutes and only then send them, but that would be pretty complicated. I will give this some more thought.

**Comment by michass** [comment]
no, if setpoint changed, then send immediately, but when setpoint is constant for 2 days dont send setpoint to this device. I can remove devices, that i dont want to change from my script, but when i change value on radiator it stay to end of the world and one day longer. I want set new temp on radiator from now to next harmonogram switch eco/comfort. I can else add condition if to my switching script.
