### ISSUE TITLE
Error: EQ-3 hardware (11) thread seems to have ended unexpectedly

### ISSUE THREAD

**Issue by michass** [mvzut/maxcube-Domoticz-plugin#3]
Hi I have this issue for few deays, and when I try to set all units at one time, I have this bug and some unit don't want to change, but in domoticz i have proper temp, that i try to set.
Now I have debug mode on.

**Comment by mvzut** [comment]
Hmmm, I sometimes have this too. I suspect it happens when the plugin's "heartbeat" takes too long, which might happen if the communication with the Cube takes a long time.
But even though I see this error occasionally, it doesn't actually stop functioning.

I'll see if I can dive into this a bit deeper

**Comment by ChrisPolewiak** [comment]
Some wired issue with onHartbeat function

Details:
Error: (EQ3) 'onHeartbeat' failed 'ValueError':'invalid literal for int() with base 10: 'null''.
Error: (EQ3) ----> Line 318 in '/opt/domoticz/plugins/MaxCube/plugin.py', function onHeartbeat
Error: (EQ3) ----> Line 277 in '/opt/domoticz/plugins/MaxCube/plugin.py', function onHeartbeat 

Please fix :) my home heating not working :-)

**Comment by mvzut** [comment]
This seems to be caused by an incorrect value of the "Min valve position for heat demand" setting of the plugin. The error message seems to suggest this value is empty, is that the case? Please set a value, e.g. 25, even if you don't use this function.

**Comment by ChrisPolewiak** [comment]
Oh right… thanks for your help :) works great
